# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: ci-build-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v2.4.0

      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v2.2.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: build
        run: make vex

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v2.4.0

      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v2.2.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: test
        run: make test
