name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    env:
      GO111MODULE: on
      COSIGN_EXPERIMENTAL: "true"

    steps:
    - name: Check out code onto GOPATH
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.0.2

    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.3.0
      with:
        go-version: 1.19
        check-latest: true

    - name: Install cosign
      uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b # v3.1.0
      with:
        install-only: true

    - name: Get TAG
      id: get_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Run goreleaser
      run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
